const DEFAULT_SETTINGS={id:'settings',currency:'INR',currencySymbol:'₹',cycleMode:'salaryDate',allowNegativeBalance:true,schemaVersion:1,categories:[
 {id:'essential',name:'Essential Expenses',percent:55,color:'#0f766e'}, {id:'guiltfree',name:'Guilt-free Spend',percent:5,color:'#f59e0b'}, {id:'debtinvest',name:'Debt Repayment / Investments',percent:10,color:'#7c3aed'}, {id:'shortsave',name:'Short-term Savings',percent:15,color:'#2563eb'}, {id:'longsave',name:'Long-term Savings',percent:15,color:'#059669'}]};
const round2=n=>Math.round((Number(n)+Number.EPSILON)*100)/100;
const dateId=d=>new Date(d).toISOString().slice(0,10);
const labelFor=d=>new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(new Date(d));
const splitIncome=(amount,categories,mode='percentage',target=null)=>{let a=round2(amount);if(mode==='fullCategory')return categories.map(c=>({categoryId:c.id,amount:c.id===target?a:0}));let result=categories.map(c=>({categoryId:c.id,amount:round2(a*c.percent/100)}));let diff=round2(a-result.reduce((s,x)=>s+x.amount,0));let largest=result.reduce((x,y)=>x.amount>=y.amount?x:y);largest.amount=round2(largest.amount+diff);return result;};
const sortedCycles=cycles=>[...cycles].sort((a,b)=>new Date(a.startDate)-new Date(b.startDate));
/* New income is the visible, spendable budget for its own cycle.  Older money
   remains a reserve and is touched only after that cycle's allocation is spent. */
const calculateBalances=(settings,incomes,expenses,cycles)=>{let carried=Object.fromEntries(settings.categories.map(c=>[c.id,0]));const out={};for(const cycle of sortedCycles(cycles)){let allocated=Object.fromEntries(settings.categories.map(c=>[c.id,0])),spent=Object.fromEntries(settings.categories.map(c=>[c.id,0]));incomes.filter(x=>x.cycleId===cycle.id).forEach(x=>x.allocations.forEach(a=>allocated[a.categoryId]=round2((allocated[a.categoryId]||0)+a.amount)));expenses.filter(x=>x.cycleId===cycle.id).forEach(x=>spent[x.categoryId]=round2((spent[x.categoryId]||0)+x.amount));out[cycle.id]=settings.categories.map(c=>{const opening=carried[c.id]||0,cycleBudget=allocated[c.id]||0,cycleSpent=spent[c.id]||0,cycleRemaining=round2(Math.max(0,cycleBudget-cycleSpent)),reserveUsed=round2(Math.max(0,cycleSpent-cycleBudget)),reserveRemaining=round2(opening-reserveUsed);return {...c,opening,allocated:cycleBudget,spent:cycleSpent,cycleRemaining,reserveUsed,reserveRemaining,closing:round2(reserveRemaining+cycleRemaining)};});carried=Object.fromEntries(out[cycle.id].map(x=>[x.id,x.closing]));}return out;};
